### ISSUE TITLE
Close out fast travel TODO comments

### ISSUE THREAD

**Issue by r-leyshon** [datasciencecampus/assess_gtfs#23]
From: https://github.com/datasciencecampus/transport-network-performance/issues/182

The following TODO comments remain outstanding in `validators.py` and `cleaners.py`, associated with fast travel:
    - [ ]  Integrate fast travel results into HTML outputs (extended outputs)
    - [ ]  Add dtype defences to `_add_validation_row()`
    - [ ]  Add datatype defences in `filter_gtfs_around_trip()`

Raised during PR #125
